-- TB_BOARD_FILE 테이블 생성 및 코멘트 추가
CREATE TABLE BOARDFILE
(
    BOARD_SEQ NUMBER NOT NULL
    , FILE_NO NUMBER NOT NULL
    , FILE_NAME_KEY VARCHAR2(200)
    , FILE_NAME VARCHAR2(100)
    , FILE_PATH VARCHAR2(200)
    , FILE_SIZE VARCHAR2(50)
    , REMARK VARCHAR(1000)
    , DEL_YN VARCHAR(1)
    , INS_USER_ID VARCHAR2(20)
    , INS_DATE DATE
    , UPD_USER_ID VARCHAR2(20)
    , UPD_DATE DATE
    , CONSTRAINT BOARDFILE_PK PRIMARY KEY
    (
     BOARD_SEQ
        , FILE_NO
        )
    ENABLE
);
 
-- TB_BOARD 테이블 샘플 데이터 조회
SELECT * FROM BOARDFILE;