
-- TB_BOARD 테이블 삭제
DROP TABLE board;
 
-- TB_BOARD 테이블 생성 및 코멘트 추가
CREATE TABLE BOARD
(
    BOARD_SEQ NUMBER NOT NULL
    , BOARD_RE_REF NUMBER
    , BOARD_RE_LEV NUMBER
    , BOARD_RE_SEQ NUMBER
    , BOARD_WRITER VARCHAR2(20)
    , BOARD_SUBJECT VARCHAR2(50)
    , BOARD_CONTENT VARCHAR2(2000)
    , BOARD_HITS NUMBER
    , DEL_YN VARCHAR(1) NOT NULL
    , INS_USER_ID VARCHAR2(20)
    , INS_DATE DATE
    , UPD_USER_ID VARCHAR2(20)
    , UPD_DATE DATE
    , CONSTRAINT TABLE1_PK PRIMARY KEY
    (
     BOARD_SEQ
        )
    ENABLE
);
-- 저장하기 위한 commit
commit;

-- 시퀀스 생성
CREATE SEQUENCE BOARD_SEQ START WITH 1 INCREMENT BY 1;


-- TB_BOARD 테이블 샘플 데이터 입력
INSERT INTO board (BOARD_RE_REF, BOARD_RE_LEV, BOARD_RE_SEQ, BOARD_WRITER, BOARD_SUBJECT, BOARD_CONTENT, INS_USER_ID, INS_DATE)
            VALUES (0, 0, 0, '게시글 작성자_1', '게시글 제목_1', '게시글 내용_1', 'NONMEMBER', sysdate, 'NONMEMBER', sysdate);

-- TB_BOARD 테이블 샘플 데이터 조회
SELECT * FROM board;
